/**
 * Machine-readable error codes — mirrors docs/API_CONTRACTS.md §9 taxonomy
 * plus the operational codes the booking engine needs.
 */
export enum ErrorCode {
  // Auth
  INVALID_PHONE = 'INVALID_PHONE',
  OTP_EXPIRED = 'OTP_EXPIRED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_SESSION_NOT_FOUND = 'OTP_SESSION_NOT_FOUND',
  OTP_MAX_ATTEMPTS = 'OTP_MAX_ATTEMPTS',
  PHONE_ALREADY_REGISTERED = 'PHONE_ALREADY_REGISTERED',
  ADMIN_REGISTRATION_PROHIBITED = 'ADMIN_REGISTRATION_PROHIBITED',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  ROLE_FORBIDDEN = 'ROLE_FORBIDDEN',

  // Bookings
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  SLOT_DOUBLE_BOOKED = 'SLOT_DOUBLE_BOOKED',
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  VERSION_CONFLICT = 'VERSION_CONFLICT',
  INVALID_BOOKING_DRAFT = 'INVALID_BOOKING_DRAFT',
  BOOKING_NOT_IN_REQUESTED_STATE = 'BOOKING_NOT_IN_REQUESTED_STATE',
  NON_CANCELLABLE_STATE = 'NON_CANCELLABLE_STATE',

  // Group bookings / fleet
  FLEET_INSUFFICIENT_AVAILABILITY = 'FLEET_INSUFFICIENT_AVAILABILITY',
  GROUP_BOOKING_NOT_FOUND = 'GROUP_BOOKING_NOT_FOUND',

  // Payments
  PAYMENT_DECLINED = 'PAYMENT_DECLINED',
  PAYMENT_SIGNATURE_MISMATCH = 'PAYMENT_SIGNATURE_MISMATCH',
  PAYMENT_ALREADY_FINALIZED = 'PAYMENT_ALREADY_FINALIZED',

  // General
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
