import { newId } from '../utils/crypto.js';
import { ROLES } from '../domain/roles.js';

const now = () => new Date().toISOString();

export const IDS = {
  customerKabir: 'a1111111-1111-4111-8111-111111111111',
  driverRajesh: 'a2222222-2222-4222-8222-222222222222',
  opsVikram: 'a3333333-3333-4333-8333-333333333333',
  customerNew: 'a4444444-4444-4444-8444-444444444444',
  driverNew: 'a5555555-5555-4555-8555-555555555555',
  customerHost: 'a6666666-6666-4666-8666-666666666666',
  driverRajeshAlt: 'a7777777-7777-4777-8777-777777777777',
  opsAlt: 'a8888888-8888-4888-8888-888888888888',
  verifyMeera: 'a9999999-9999-4999-8999-999999999999',
  financeArjun: 'aa101010-1010-4101-8101-101010101010',
  superHq: 'aa121212-1212-4121-8121-121212121212',
  customerSuspended: 'aa131313-1313-4131-8131-131313131313',
  driverStandby: 'aa141414-1414-4141-8141-141414141414',
  fleetOwner: 'aa151515-1515-4151-8151-151515151515',
  policyDefault: 'b0000000-0000-4000-8000-000000000001',
  vehicleEclass: 'e0000000-0000-4000-8000-000000000001',
  vehicle5series: 'e0000000-0000-4000-8000-000000000002',
  vehicleHycross: 'e0000000-0000-4000-8000-000000000003',
  vehicleInnova2: 'e0000000-0000-4000-8000-000000000004',
  vehicleInnova3: 'e0000000-0000-4000-8000-000000000005',
  vehicleCamry: 'e0000000-0000-4000-8000-000000000006',
  vehicleVintage: 'e0000000-0000-4000-8000-000000000007',
  addonBandhgala: 'd0000000-0000-4000-8000-000000000001',
  addonFloral: 'd0000000-0000-4000-8000-000000000002',
  addonPrivacy: 'd0000000-0000-4000-8000-000000000003',
  addonVipTray: 'd0000000-0000-4000-8000-000000000004',
};

export function buildSeed() {
  const createdAt = now();

  const users = [
    {
      id: IDS.customerKabir,
      phoneNumber: '+919810000001',
      email: 'kabir.sharma@example.com',
      fullName: 'Kabir Sharma',
      role: ROLES.CUSTOMER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.driverRajesh,
      phoneNumber: '+919810000002',
      email: 'rajesh.singh@example.com',
      fullName: 'Rajesh Singh',
      role: ROLES.DRIVER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.opsVikram,
      phoneNumber: '+919810000003',
      email: 'vikram.malhotra@shadidriver.com',
      fullName: 'Vikram Malhotra',
      role: ROLES.OPERATIONS_ADMIN,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.customerNew,
      phoneNumber: '+919810000004',
      email: 'new.customer@example.com',
      fullName: 'New Customer',
      role: ROLES.CUSTOMER,
      accountStatus: 'profileIncomplete',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.driverNew,
      phoneNumber: '+919810000005',
      email: 'new.driver@example.com',
      fullName: 'New Chauffeur Applicant',
      role: ROLES.DRIVER,
      accountStatus: 'profileIncomplete',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.customerHost,
      phoneNumber: '+919876543210',
      email: 'host@example.com',
      fullName: 'Kabir Sharma',
      role: ROLES.CUSTOMER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.driverRajeshAlt,
      phoneNumber: '+919876500002',
      email: 'rajesh.alt@example.com',
      fullName: 'Rajesh Singh',
      role: ROLES.DRIVER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.opsAlt,
      phoneNumber: '+919876500003',
      email: 'ops.alt@shadidriver.com',
      fullName: 'Vikram Malhotra',
      role: ROLES.OPERATIONS_ADMIN,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.verifyMeera,
      phoneNumber: '+919810000009',
      email: 'verify.admin@shadidriver.com',
      fullName: 'Meera Kapoor',
      role: ROLES.VERIFICATION_ADMIN,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.financeArjun,
      phoneNumber: '+919810000007',
      email: 'finance.admin@shadidriver.com',
      fullName: 'Arjun Mehta',
      role: ROLES.FINANCE_ADMIN,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.superHq,
      phoneNumber: '+919810000099',
      email: 'super.admin@shadidriver.com',
      fullName: 'ShadiDriver HQ',
      role: ROLES.SUPER_ADMIN,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.customerSuspended,
      phoneNumber: '+919810000006',
      email: 'suspended@example.com',
      fullName: 'Suspended User',
      role: ROLES.CUSTOMER,
      accountStatus: 'suspended',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.driverStandby,
      phoneNumber: '+919810000008',
      email: 'aman.verma@example.com',
      fullName: 'Aman Verma',
      role: ROLES.DRIVER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
    {
      id: IDS.fleetOwner,
      phoneNumber: '+919810000010',
      email: 'fleet@shadidriver.com',
      fullName: 'Royal Heritage Agency',
      role: ROLES.FLEET_OWNER,
      accountStatus: 'active',
      isPhoneVerified: true,
      createdAt,
    },
  ];

  const customers = {
    [IDS.customerKabir]: {
      id: IDS.customerKabir,
      city: 'Delhi',
      preferredLanguage: 'en',
      emergencyContactName: 'Ananya Sharma',
      emergencyContactPhone: '+919810009001',
      weddingPreferences: 'Baraat lead car, slow procession',
      profilePhotoUrl: null,
    },
    [IDS.customerNew]: {
      id: IDS.customerNew,
      city: '',
      preferredLanguage: 'en',
      emergencyContactName: null,
      emergencyContactPhone: null,
      weddingPreferences: null,
      profilePhotoUrl: null,
    },
    [IDS.customerHost]: {
      id: IDS.customerHost,
      city: 'Delhi',
      preferredLanguage: 'en',
      emergencyContactName: 'Ananya Sharma',
      emergencyContactPhone: '+919810009001',
      weddingPreferences: null,
      profilePhotoUrl: null,
    },
    [IDS.customerSuspended]: {
      id: IDS.customerSuspended,
      city: 'Delhi',
      preferredLanguage: 'en',
      emergencyContactName: null,
      emergencyContactPhone: null,
      weddingPreferences: null,
      profilePhotoUrl: null,
    },
  };

  const drivers = {
    [IDS.driverRajesh]: {
      id: IDS.driverRajesh,
      dateOfBirth: '1988-03-12',
      experienceYears: 12,
      licenseNumber: 'DL-07-20140012345',
      languagesSpoken: ['Hindi', 'English', 'Punjabi'],
      ceremonialAttireSizes: { suit: '42R', safa: 'L', height_cm: 180 },
      dutyStatus: 'AVAILABLE',
      verificationStatus: 'APPROVED',
      isOnline: true,
      averageRating: 4.9,
      totalTripsCompleted: 186,
      bio: 'Wedding specialist chauffeur with 12 years of baraat and vidai experience across Delhi NCR.',
      operatingArea: 'Delhi NCR',
      weddingExperienceYears: 8,
      documentStatus: 'VERIFIED',
      vehicleStatus: 'ASSIGNED_MERCEDES_ECLASS',
      policeClearanceStatus: 'CLEARED',
      ceremonialAttireStatus: 'READY',
      identityVerified: true,
      profileImageUrl: null,
    },
    [IDS.driverRajeshAlt]: {
      id: IDS.driverRajeshAlt,
      dateOfBirth: '1988-03-12',
      experienceYears: 12,
      licenseNumber: 'DL-07-20140019999',
      languagesSpoken: ['Hindi', 'English'],
      ceremonialAttireSizes: { suit: '42R', safa: 'L', height_cm: 180 },
      dutyStatus: 'AVAILABLE',
      verificationStatus: 'APPROVED',
      isOnline: true,
      averageRating: 4.9,
      totalTripsCompleted: 186,
      bio: 'Wedding specialist chauffeur.',
      operatingArea: 'Delhi NCR',
      weddingExperienceYears: 8,
      documentStatus: 'VERIFIED',
      vehicleStatus: 'ASSIGNED_MERCEDES_ECLASS',
      policeClearanceStatus: 'CLEARED',
      ceremonialAttireStatus: 'READY',
      identityVerified: true,
      profileImageUrl: null,
    },
    [IDS.driverNew]: {
      id: IDS.driverNew,
      dateOfBirth: '1995-01-01',
      experienceYears: 3,
      licenseNumber: 'DL-07-PENDING0001',
      languagesSpoken: ['Hindi'],
      ceremonialAttireSizes: {},
      dutyStatus: 'OFFLINE',
      verificationStatus: 'PENDING_SUBMISSION',
      isOnline: false,
      averageRating: 5,
      totalTripsCompleted: 0,
      bio: '',
      operatingArea: '',
      weddingExperienceYears: 0,
      documentStatus: 'PENDING_SUBMISSION',
      vehicleStatus: '',
      policeClearanceStatus: 'PENDING',
      ceremonialAttireStatus: 'PENDING',
      identityVerified: false,
      profileImageUrl: null,
    },
    [IDS.driverStandby]: {
      id: IDS.driverStandby,
      dateOfBirth: '1990-06-18',
      experienceYears: 9,
      licenseNumber: 'DL-07-20180044521',
      languagesSpoken: ['Hindi', 'English'],
      ceremonialAttireSizes: { suit: '40R', safa: 'M', height_cm: 176 },
      dutyStatus: 'AVAILABLE_NOW',
      verificationStatus: 'APPROVED',
      isOnline: true,
      averageRating: 4.8,
      totalTripsCompleted: 92,
      bio: 'Standby ceremonial chauffeur for emergency replacement across Delhi NCR.',
      operatingArea: 'Delhi NCR',
      weddingExperienceYears: 6,
      documentStatus: 'VERIFIED',
      vehicleStatus: 'ASSIGNED_BMW_5SERIES',
      policeClearanceStatus: 'CLEARED',
      ceremonialAttireStatus: 'READY',
      identityVerified: true,
      profileImageUrl: null,
    },
  };

  const admins = {
    [IDS.opsVikram]: {
      department: 'Operations Control Room',
      authorizationLevel: 'OPS_L3',
      photoUrl: null,
    },
    [IDS.opsAlt]: {
      department: 'Operations Control Room',
      authorizationLevel: 'OPS_L3',
      photoUrl: null,
    },
    [IDS.verifyMeera]: {
      department: 'KYC & Verification',
      authorizationLevel: 'VERIFY_L2',
      photoUrl: null,
    },
    [IDS.financeArjun]: {
      department: 'Finance & Settlements',
      authorizationLevel: 'FIN_L2',
      photoUrl: null,
    },
    [IDS.superHq]: {
      department: 'Platform HQ',
      authorizationLevel: 'SUPER',
      photoUrl: null,
    },
  };

  const categories = [
    {
      id: 'SVC_BARAAT',
      name: 'Baraat Procession',
      description: 'Groom procession with luxury chauffeur, safa coordination, and slow ceremonial pace.',
      iconUrl: null,
      assetPath: 'assets/categories/baraat.png',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: 'SVC_VIDAI',
      name: 'Vidai',
      description: 'Emotional farewell transfer for the bride with discreet, experienced chauffeur.',
      iconUrl: null,
      assetPath: 'assets/categories/vidai.png',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: 'SVC_ENTRY',
      name: 'Bride & Groom Entry',
      description: 'Grand venue arrival for pheras, reception, or sangeet entry.',
      iconUrl: null,
      assetPath: 'assets/categories/entry.png',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: 'SVC_RECEPTION',
      name: 'Reception VIP',
      description: 'Guest and VIP shuttle for reception hospitality.',
      iconUrl: null,
      assetPath: 'assets/categories/reception.png',
      displayOrder: 4,
      isActive: true,
    },
    {
      id: 'SVC_MULTIDAY',
      name: 'Multi-Day Wedding',
      description: '2–5 day wedding coverage split into chauffeur shift segments.',
      iconUrl: null,
      assetPath: 'assets/categories/multiday.png',
      displayOrder: 5,
      isActive: true,
    },
  ];

  const addons = [
    {
      id: IDS.addonBandhgala,
      serviceCategoryId: 'SVC_BARAAT',
      name: 'Royal Bandhgala + Safa',
      description: 'Chauffeur ceremonial bandhgala with coordinated safa.',
      pricePaise: 150000,
      isActive: true,
      features: ['Bandhgala', 'Safa', 'Brooch'],
      assetPath: null,
    },
    {
      id: IDS.addonFloral,
      serviceCategoryId: 'SVC_BARAAT',
      name: 'Floral Car Coordination',
      description: 'Fresh marigold and rose garland setup on bonnet and roof rails.',
      pricePaise: 250000,
      isActive: true,
      features: ['Garlands', 'Bonnet decor'],
      assetPath: null,
    },
    {
      id: IDS.addonPrivacy,
      serviceCategoryId: 'SVC_VIDAI',
      name: 'Privacy Partition & Soft Lighting',
      description: 'Discreet cabin lighting and privacy for vidai transfer.',
      pricePaise: 120000,
      isActive: true,
      features: ['Cabin lighting', 'Privacy'],
      assetPath: null,
    },
    {
      id: IDS.addonVipTray,
      serviceCategoryId: 'SVC_RECEPTION',
      name: 'VIP Water & Amenities Tray',
      description: 'Bottled water, mints, and welcome towels for guests.',
      pricePaise: 80000,
      isActive: true,
      features: ['Water', 'Towels'],
      assetPath: null,
    },
  ];

  const policies = [
    {
      id: IDS.policyDefault,
      policyName: 'Default Ceremonial Policy',
      advanceTokenPercentage: 25,
      cancellationTiers: [
        { hours_before: 168, refund_percent: 100 },
        { hours_before: 72, refund_percent: 75 },
        { hours_before: 24, refund_percent: 50 },
        { hours_before: 0, refund_percent: 0 },
      ],
      gracePeriodMinutes: 30,
      overtimeIncrementMinutes: 30,
      isDefault: true,
    },
  ];

  const yesterday = new Date(Date.now() - 86_400_000).toISOString();
  const pricingRules = [
    { id: 'c0000000-0000-4000-8000-000000000001', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'LUXURY_SEDAN', cityCode: 'DEL', baseHours: 5, baseKm: 50, baseRatePaise: 1200000, extraHourRatePaise: 250000, extraKmRatePaise: 4000, nightAllowancePaise: 150000, muhuratMultiplier: 1.15, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000002', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'ULTRA_LUXURY', cityCode: 'DEL', baseHours: 5, baseKm: 50, baseRatePaise: 2200000, extraHourRatePaise: 400000, extraKmRatePaise: 6000, nightAllowancePaise: 250000, muhuratMultiplier: 1.15, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000003', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'VINTAGE', cityCode: 'DEL', baseHours: 5, baseKm: 40, baseRatePaise: 1800000, extraHourRatePaise: 350000, extraKmRatePaise: 5000, nightAllowancePaise: 200000, muhuratMultiplier: 1.2, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000004', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'EXECUTIVE_MPV', cityCode: 'DEL', baseHours: 5, baseKm: 60, baseRatePaise: 900000, extraHourRatePaise: 180000, extraKmRatePaise: 3000, nightAllowancePaise: 100000, muhuratMultiplier: 1.1, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000005', serviceCategoryId: 'SVC_VIDAI', vehicleClass: 'LUXURY_SEDAN', cityCode: 'DEL', baseHours: 4, baseKm: 40, baseRatePaise: 1000000, extraHourRatePaise: 220000, extraKmRatePaise: 4000, nightAllowancePaise: 150000, muhuratMultiplier: 1.1, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000006', serviceCategoryId: 'SVC_ENTRY', vehicleClass: 'LUXURY_SEDAN', cityCode: 'DEL', baseHours: 3, baseKm: 30, baseRatePaise: 800000, extraHourRatePaise: 220000, extraKmRatePaise: 4000, nightAllowancePaise: 100000, muhuratMultiplier: 1.1, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000007', serviceCategoryId: 'SVC_RECEPTION', vehicleClass: 'EXECUTIVE_MPV', cityCode: 'DEL', baseHours: 6, baseKm: 80, baseRatePaise: 1100000, extraHourRatePaise: 160000, extraKmRatePaise: 2500, nightAllowancePaise: 120000, muhuratMultiplier: 1.05, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000008', serviceCategoryId: 'SVC_MULTIDAY', vehicleClass: 'LUXURY_SEDAN', cityCode: 'DEL', baseHours: 8, baseKm: 100, baseRatePaise: 2800000, extraHourRatePaise: 250000, extraKmRatePaise: 4000, nightAllowancePaise: 200000, muhuratMultiplier: 1, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000011', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'LUXURY_SEDAN', cityCode: 'JAI', baseHours: 5, baseKm: 50, baseRatePaise: 1100000, extraHourRatePaise: 230000, extraKmRatePaise: 3800, nightAllowancePaise: 140000, muhuratMultiplier: 1.15, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000012', serviceCategoryId: 'SVC_BARAAT', vehicleClass: 'ULTRA_LUXURY', cityCode: 'JAI', baseHours: 5, baseKm: 50, baseRatePaise: 2000000, extraHourRatePaise: 380000, extraKmRatePaise: 5500, nightAllowancePaise: 230000, muhuratMultiplier: 1.15, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000013', serviceCategoryId: 'SVC_ENTRY', vehicleClass: 'ULTRA_LUXURY', cityCode: 'DEL', baseHours: 3, baseKm: 30, baseRatePaise: 1800000, extraHourRatePaise: 350000, extraKmRatePaise: 5000, nightAllowancePaise: 200000, muhuratMultiplier: 1.1, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000014', serviceCategoryId: 'SVC_RECEPTION', vehicleClass: 'LUXURY_SEDAN', cityCode: 'DEL', baseHours: 6, baseKm: 80, baseRatePaise: 1400000, extraHourRatePaise: 220000, extraKmRatePaise: 3500, nightAllowancePaise: 150000, muhuratMultiplier: 1.05, effectiveFrom: yesterday, isActive: true },
    { id: 'c0000000-0000-4000-8000-000000000015', serviceCategoryId: 'SVC_VIDAI', vehicleClass: 'ULTRA_LUXURY', cityCode: 'DEL', baseHours: 4, baseKm: 40, baseRatePaise: 1800000, extraHourRatePaise: 350000, extraKmRatePaise: 5000, nightAllowancePaise: 200000, muhuratMultiplier: 1.1, effectiveFrom: yesterday, isActive: true },
  ];

  const vehicles = [
    {
      id: IDS.vehicleEclass,
      fleetCode: 'SD-DEL-001',
      independentDriverId: IDS.driverRajesh,
      ownerName: 'Royal Heritage Agency',
      make: 'Mercedes-Benz',
      model: 'E-Class',
      year: 2023,
      color: 'Obsidian Black',
      registrationNumber: 'DL1CA1234',
      seatingCapacity: 4,
      fuelType: 'PETROL',
      vehicleClass: 'LUXURY_SEDAN',
      isVintage: false,
      basePricePaise: 1200000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/eclass.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/eclass.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Dual climate', 'Ambient lighting', 'Champagne cooler'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Ideal for baraat lead car and vidai.',
      suitableCeremonies: ['SVC_BARAAT', 'SVC_VIDAI', 'SVC_ENTRY'],
    },
    {
      id: IDS.vehicle5series,
      fleetCode: 'SD-DEL-002',
      independentDriverId: IDS.driverStandby,
      ownerName: 'Royal Heritage Agency',
      make: 'BMW',
      model: '5 Series',
      year: 2022,
      color: 'Mineral White',
      registrationNumber: 'DL1CA5678',
      seatingCapacity: 4,
      fuelType: 'PETROL',
      vehicleClass: 'ULTRA_LUXURY',
      isVintage: false,
      basePricePaise: 2200000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/5series.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/5series.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Massage seats', 'Panoramic roof'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Ultra luxury entry and VIP reception.',
      suitableCeremonies: ['SVC_ENTRY', 'SVC_RECEPTION', 'SVC_BARAAT'],
    },
    {
      id: IDS.vehicleHycross,
      fleetCode: 'SD-DEL-003',
      independentDriverId: IDS.driverRajeshAlt,
      ownerName: 'PB Ceremonial Fleet',
      make: 'Toyota',
      model: 'Innova Hycross',
      year: 2024,
      color: 'Pearl White',
      registrationNumber: 'DL1CA9012',
      seatingCapacity: 7,
      fuelType: 'HYBRID',
      vehicleClass: 'EXECUTIVE_MPV',
      isVintage: false,
      basePricePaise: 900000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/hycross.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/hycross.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Captain seats', 'Dual AC'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Family and guest shuttle for reception and multi-day.',
      suitableCeremonies: ['SVC_RECEPTION', 'SVC_MULTIDAY'],
    },
    {
      id: IDS.vehicleInnova2,
      fleetCode: 'SD-DEL-004',
      independentDriverId: null,
      ownerName: 'PB Ceremonial Fleet',
      make: 'Toyota',
      model: 'Innova Crysta',
      year: 2023,
      color: 'White',
      registrationNumber: 'DL1CA3344',
      seatingCapacity: 7,
      fuelType: 'DIESEL',
      vehicleClass: 'EXECUTIVE_MPV',
      isVintage: false,
      basePricePaise: 850000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/innova.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/innova.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Captain seats', 'Dual AC'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Guest shuttle for baraat and reception convoys.',
      suitableCeremonies: ['SVC_RECEPTION', 'SVC_BARAAT', 'SVC_MULTIDAY'],
    },
    {
      id: IDS.vehicleInnova3,
      fleetCode: 'SD-DEL-005',
      independentDriverId: null,
      ownerName: 'PB Ceremonial Fleet',
      make: 'Toyota',
      model: 'Innova Crysta',
      year: 2022,
      color: 'Silver',
      registrationNumber: 'DL1CA7788',
      seatingCapacity: 7,
      fuelType: 'DIESEL',
      vehicleClass: 'EXECUTIVE_MPV',
      isVintage: false,
      basePricePaise: 850000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/innova2.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/innova2.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Captain seats'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Additional convoy unit for large guest counts.',
      suitableCeremonies: ['SVC_RECEPTION', 'SVC_MULTIDAY'],
    },
    {
      id: IDS.vehicleCamry,
      fleetCode: 'SD-DEL-006',
      independentDriverId: null,
      ownerName: 'Royal Heritage Agency',
      make: 'Toyota',
      model: 'Camry',
      year: 2023,
      color: 'Black',
      registrationNumber: 'DL1CA2211',
      seatingCapacity: 4,
      fuelType: 'HYBRID',
      vehicleClass: 'LUXURY_SEDAN',
      isVintage: false,
      basePricePaise: 1100000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/camry.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/camry.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Leather seats', 'Quiet cabin'],
      transmission: 'AUTOMATIC',
      suitabilityInfo: 'Discreet vidai and family transfer sedan.',
      suitableCeremonies: ['SVC_VIDAI', 'SVC_ENTRY', 'SVC_RECEPTION'],
    },
    {
      id: IDS.vehicleVintage,
      fleetCode: 'SD-DEL-007',
      independentDriverId: IDS.driverRajesh,
      ownerName: 'Royal Heritage Agency',
      make: 'Hindustan',
      model: 'Ambassador',
      year: 1968,
      color: 'Ivory',
      registrationNumber: 'DL1CA1968',
      seatingCapacity: 4,
      fuelType: 'PETROL',
      vehicleClass: 'VINTAGE',
      isVintage: true,
      basePricePaise: 1800000,
      city: 'Delhi',
      imageUrl: 'https://cdn.shadidriver.local/vehicles/ambassador.jpg',
      galleryUrls: ['https://cdn.shadidriver.local/vehicles/ambassador.jpg'],
      verificationStatus: 'APPROVED',
      isAvailable: true,
      isActive: true,
      amenities: ['Heritage interior', 'Floral ready'],
      transmission: 'MANUAL',
      suitabilityInfo: 'Heritage baraat lead car.',
      suitableCeremonies: ['SVC_BARAAT', 'SVC_ENTRY'],
    },
  ];

  const reviews = [
    {
      id: newId(),
      driverId: IDS.driverRajesh,
      reviewerName: 'Ananya K.',
      rating: 5,
      comment: 'Impeccable baraat pace and grooming. Family felt looked after the entire evening.',
      createdAt: new Date(Date.now() - 12 * 86_400_000).toISOString(),
    },
    {
      id: newId(),
      driverId: IDS.driverRajesh,
      reviewerName: 'Rohit S.',
      rating: 4.8,
      comment: 'Vidai transfer was discreet and calm. Highly recommended.',
      createdAt: new Date(Date.now() - 30 * 86_400_000).toISOString(),
    },
  ];

  const addresses = [
    {
      id: newId(),
      customerId: IDS.customerKabir,
      label: 'Home',
      address: '12, Golf Links, New Delhi',
      landmark: 'Near Khan Market',
      type: 'home',
      isDefault: true,
    },
    {
      id: newId(),
      customerId: IDS.customerKabir,
      label: 'Imperial Banquets',
      address: 'Grand Imperial Banquets, MG Road, New Delhi',
      landmark: 'Gate 2 VIP Entrance',
      type: 'weddingVenue',
      isDefault: false,
    },
  ];

  return {
    users,
    customers,
    drivers,
    admins,
    categories,
    addons,
    policies,
    pricingRules,
    vehicles,
    reviews,
    addresses,
  };
}
